config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

  resources :reviews

  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :reviews
	
	has_secure_password

    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
    validates :license_plate_state, presence: true
    validates :license_plate_number, presence: true
    validates :vehicle_image, presence: true

	
	# paperclip gem
	has_attached_file :vehicle_image,
					  :styles => { 
					  	:medium => "300x300>", 
					  	:thumb => "100x100>" }, 
					  :default_url => "/images/:style/missing.png"

	 # paperclip required validation
    validates_attachment_content_type :vehicle_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

	# This allows us to invoke the current_user() method in views!
    helper_method :current_user, :logged_in?

    def current_user

    	if @current_user
    		return @current_user
    	end

    	if session[:current_user_id]
    		@current_user = User.find session[:current_user_id]
    	else
    		@current_user = nil
    	end

    	return @current_user

    end


    # Q: Why only works with @ ommitted?
    def logged_in?
    	current_user != nil
    end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index

		@review = Review.new

		if !current_user
			@user = User.new
			redirect_to root_path
		end

		render json: Review.where("reviewed_plate_number = '#{current_user.license_plate_number}'")
	end


	def new
		@review = Review.new

		if !current_user
			@user = User.new
			redirect_to root_path
		end

		
	end


	def create
		@review = Review.new review_params
		if @review.save
			redirect_to root_path
		else
			render :new
		end
	end


	def show
		render json: Review.find(params[:id]).to_json
	end

	private

	def review_params
		params.require(:review).permit(
			:reviewer_id,
			:reviewer_location,
			:reviewed_plate_state,
			:reviewed_plate_number,
			:aggressive_speeding,
			:aggressive_weaving,
			:aggressive_tailgating,
			:aggressive_cutting,
			:aggressive_rage,
			:aggressive_other,
			:inattentive_braking,
			:inattentive_drifting,
			:inattentive_phone,
			:inattentive_pedestrian,
			:inattentive_drunk,
			:inattentive_other,
			:alert_safe,
			:alert_courteous,
			:parking_blocking,
			:parking_illegal
		)
	end	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	# New session created on Login (i.e. user is found)
	def create
		@user = User.find_by :email => params[:email]

		if @user.nil?
		    flash[:error] = "No such user."
		    # redirect_to users_path
		elsif @user.authenticate params[:password]
		    session[:current_user_id] = @user.id
		    flash[:notice] = "Thank you for logging in, #{@user.email}."
		else
		    flash[:error] = "Incorrect password."
		    # redirect_to users_path
		end
		redirect_to user_path(:id)
	end


	def destroy
		session[:current_user_id] = nil
		flash[:notice] = "You have been logged out."

		redirect_to root_path
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
		@user = User.new
		if current_user
			redirect_to user_path(:id)
		end

	end

	# New user created on Register
	def create
		@user = User.new user_params

		if @user.save
			session[:current_user_id] = @user.id
			redirect_to user_path(:id) 
		else
			render :index
		end
	end


	def show
		if !current_user
			redirect_to users_path and return
		end

		respond_to do |format|
			format.html

			format.json do
				render json: Review.all
			end

			format.xml do
				render xml: current_user
			end
		end
	end


	private

	def user_params
		params.require(:user).permit(
			:email,
			:password,
			:password_confirmation,
			:license_plate_state,
			:license_plate_number,
			:vehicle_image
		)
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cd_helper.rb
module CdHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pl8rR8r</title>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


<footer .navbar-static-top .container .navbar-fixed-top .navbar-fixed-bottom>
	<hr>
	<div class="container">
		<div>by: Doug Stockalper, WDI Aug 2014</div>
		<div>Stack: Postgres, Ruby, Rails, Javascript, Angular, Bootstrap</div>
		<div>API's: Paperclip, Geocoder, Google Maps</div>
	</div>
</footer>
	
</body>
</html>

app/views/reviews/_nav_show.html.erb
<nav class="navbar navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
	<div class="container" ng-app="tattle" ng-controller="TattleController as ctrl">

	<div class="navbar-header">
		<a class="navbar-brand" href=""><%= current_user.email%></a>
	</div>

	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<div class="collapse navbar-collapse">

			<ul class="nav navbar-nav">
				<li class="inactive">
					<%= link_to ' My Dashboard', user_path(:id), :class=>"fa fa-tachometer" %>
				</li>
				<li class="inactive">
					<a href="#"><i class="fa fa-cog"> Edit Profile</i></a>
				</li>
				<li class="inactive"> 
					<%= link_to ' Logout', sessions_path, method: :delete, :class=>"fa fa-lock" %>
				</li>	
			</ul>

			<ul class="nav navbar-nav navbar-right">
            	<li class="active"> 
              		<%= link_to ' Rate a Driver', new_review_path, :class=>"fa fa-car" %>
              	</li>	
            </ul>

		</div>

	</div>
</nav>

app/views/reviews/_search_pane.html.erb
<%= form_for @review, html: {class: "form-horizontal"} do |f| %>
		
	<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div>State</div>
					<%= f.select :reviewed_plate_state, 
						["AL", "AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC","Other"] %>
					<%= f.text_field :reviewed_plate_number, :placeholder=>"License Plate Number" %>
					<img src="#">
				</div>

				<!-- geolocation button -->
				<div class="col-md-6">
					<input type="button" value="Stamp Location" onclick="showlocation()"/> 

					<br>
					Latitude: <span id="latitude">..</span><br>
					Longitude: <span id="longitude">..</span>

					<SCRIPT>
					function showlocation(){
						navigator.geolocation.watchPosition(callback);
					}
					function callback(position){
						document.getElementById('latitude').innerHTML=position.coords.latitude;
						document.getElementById('longitude').innerHTML=position.coords.longitude;
					}
					</SCRIPT>
				</div>	
				
			</div>
				<br><br><br><br>
			
				<div class="row">
					<div class="col-md-3">
						<div>Aggressive</div>
						<%= f.label "Speeding" %> 
				        <%= f.check_box :aggressive_speeding %> <br />
				        <%= f.label "Weaving" %> 
				        <%= f.check_box :aggressive_weaving %> <br />
				        <%= f.label "Tailgating" %> 
				        <%= f.check_box :aggressive_tailgating %> <br />
				        <%= f.label "Cutting in Front" %> 
				        <%= f.check_box :aggressive_cutting %> <br />
				        <%= f.label "Road Rage" %> 
				        <%= f.check_box :aggressive_rage %> <br />
				        <%= f.label "Other Aggressive" %> 
				        <%= f.check_box :aggressive_other %> <br />
			    	</div>
			    	<div class="col-md-3">
						<div>Inattentive</div>
						<%= f.label "Sudden Braking" %> 
				        <%= f.check_box :inattentive_braking %> <br />
				        <%= f.label "Drifting" %> 
				        <%= f.check_box :inattentive_drifting %> <br />
				        <%= f.label "Phone / Makeup / Kids" %> 
				        <%= f.check_box :inattentive_phone %> <br />
				        <%= f.label "Pedestrian Encounter" %> 
				        <%= f.check_box :inattentive_pedestrian %> <br />
				        <%= f.label "Drunk Driving" %> 
				        <%= f.check_box :inattentive_drunk %> <br />
				        <%= f.label "Other Inattentive" %> 
				        <%= f.check_box :inattentive_other %> <br />
			    	</div>
			    	<div class="col-md-3">
						<div>Alert</div>
						<%= f.label "Safe" %> 
				        <%= f.check_box :alert_safe %> <br />
				        <%= f.label "Courteous" %> 
				        <%= f.check_box :alert_courteous %> <br />
			    	</div>
			    	<div class="col-md-3">
						<div>Parking</div>
						<%= f.label "Illegal" %> 
				        <%= f.check_box :parking_illegal %> <br />
				        <%= f.label "Blocking" %> 
				        <%= f.check_box :parking_blocking %> <br />
			    	</div>
				</div>


		<br><br><br><br>
		<%= f.submit %>
		<br><br>

		<% end %>
				
	</div>
		

        

app/views/reviews/index.html.erb
<h3>Review index.html</h3>

app/views/reviews/new.html.erb
<%= render partial: 'nav_show' %>

<!-- av bar is currently obscuring part of body.  unable to style body in application.css.sass.  Uing <br> for now -->
<br><br><br><br><br>
<%= render partial: 'search_pane' %>

app/views/shared/_form_error_list.html.erb
<% if model.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(model.errors.count, "error") %></h2>
        <ul>
            <% model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_landing_page.html.erb
<div class="jumbotron">
	
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<h1>PlaterRater</h1>
				<p><b>Promote safe and courteous driving by reviewing fellow motorists - via their license plate number</b></p>
				
			</div>
			<div class="col-md-6">
				<div class="col-md-6">
					<img class="landing_img"src="http://cdn.fairfaxregional.com.au/storypad-5KuvS37emzbaPy9XbUJavA/aa5b61b2-f8df-427a-a542-63ffc0bdd193.jpg">
					<figcaption>Review other drivers</figcaption>
				</div>
				<div class="col-md-6">
					<img src="">
					<img class="landing_img" src="http://t0.gstatic.com/images?q=tbn:ANd9GcSrY9PHj1SAdZQsOz9Y-aVJE7Rk0p0HQ8Xl1H-gAfDCFNBz_t9H">
					<figcaption>Monitor how others rate you</figcaption>
				</div>
				
				
			</div>
		</div>
		
	</div>
</div>

<div n></div>

app/views/users/_map_corner.html.erb
<img class="mapDisplay" src="https://maps.googleapis.com/maps/api/staticmap?center=-15.800513,-47.91378&zoom=11&size=200x200">

app/views/users/_nav_index.html.erb
<div class="navbar navbar navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse"></button>
			<a class="navbar-brand" href="#"></a>
		</div>
		<div class="navbar-collapse collapse">

				<%= form_tag sessions_path, class: "navbar-form navbar-right" do %>
					<div class="form-group">
				        <%= text_field_tag :email, nil, placeholder: "email", class: "form-control" %>
				    </div>
				    <div class="form-group">
				        <%= password_field_tag :password, nil, placeholder: "password", class: "form-control"  %>
				      </div>
				        <%= submit_tag "Login", class: "btn btn-success"%>

				<% end %>

		</div>
	</div>
</div>

app/views/users/_nav_show.html.erb
<nav class="navbar navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
	<div class="container">

		<div class="navbar-header">
			<a class="navbar-brand" href=""><%= current_user.email%></a>
		</div>

		<div class="collapse navbar-collapse navbar-ex1-collapse">
    		<div class="collapse navbar-collapse">

	            <ul class="nav navbar-nav">
	              <li class="active">
	              	<a href="#"><i class="fa fa-tachometer"> My Dashboard</i></a>
	              </li>
	              <li class="inactive">
	              	<a href="#"><i class="fa fa-cog"> Edit Profile</i></a>
	              </li>
	              <li class="inactive"> 
	              	<%= link_to ' Logout', sessions_path, method: :delete, :class=>"fa fa-lock" %>
	              </li>	
	            </ul>

	            <ul class="nav navbar-nav navbar-right">
	            	<li class="inactive"> 
	              		<%= link_to ' Rate a Driver', new_review_path, :class=>"fa fa-car" %>
	              	</li>	
	            </ul>
	            
	         </div>
         </div>

	</div>
</nav>

app/views/users/_profile_corner.html.erb
<% if logged_in? %>           
	Logged in as <%= current_user.email %><br>
	Vehicle Image: <br><%= image_tag current_user.vehicle_image.url(:medium) %><br>
    <div class="license_plate"><span class="license_text"><%= current_user.license_plate_number %></span></div><br>
<% end %>

app/views/users/_score_overall_corner.html.erb
<h4>score overall corner</h4>

app/views/users/_score_reviews_corner.html.erb
<section ng-controller="RevController as ctrl">
	<div>
		<table class="table table-condensed" border="3">
			<thead>
			<tr>
				<th></th>
				<th></th>
				<th colspan="5" class="reviewTableCategory aggressive">Aggressive</th>
				<th colspan="4" class="reviewTableCategory inattentive">Inattentive</th>
				<th colspan="2" class="reviewTableCategory alert">Alert</th>
			</tr>
			<tr>
				<th class="reviewTableHeader">Date</th>
				<th class="reviewTableHeader">Time</th>
				<th class="reviewTableHeader aggressive">Sp</th>
				<th class="reviewTableHeader aggressive">Wv</th>
				<th class="reviewTableHeader aggressive">TG</th>
				<th class="reviewTableHeader aggressive">Ct</th>
				<th class="reviewTableHeader aggressive">O</th>
				<th class="reviewTableHeader inattentive">Br</th>
				<th class="reviewTableHeader inattentive">Dr</th>
				<th class="reviewTableHeader inattentive">Ph</th>
				<th class="reviewTableHeader inattentive">DD</th>
				<th class="reviewTableHeader alert">Sf</th>
				<th class="reviewTableHeader alert">Cr</th>
			</tr>	
			</thead>
			<tbody>
			<tr ng-repeat="review in ctrl.allCurrentUserReviews | orderBy: '-created_at' | limitTo: 10">
				<td class="reviewTableBody">{{ review.created_at | date: 'shortDate'}}</td>
				<td class="reviewTableBody">{{ review.created_at | date: 'HH:mm'}}</td>
				<td class="reviewTableBody aggressive">{{review.aggressive_speeding===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody aggressive">{{review.aggressive_weaving===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody aggressive">{{review.aggressive_tailgating===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody aggressive">{{review.aggressive_cutting===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody aggressive">{{review.aggressive_other===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody inattentive">{{review.inattentive_braking===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody inattentive">{{review.inattentive_drifting===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody inattentive">{{review.inattentive_phone===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody inattentive">{{review.inattentive_drunk===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody alert">{{review.alert_safe===1 ? "&#x2713;" : ""}}</td>
				<td class="reviewTableBody alert">{{review.alert_courteous===1 ? "&#x2713;" : ""}}</td>
			</tr>
			</tbody>
		</table>

		<table class="table table-condensed">
		    <thead>
		        <tr>
		            <th>Legend</th>
		        </tr>
		    </thead>
		    <tbody>
		        <tr>
		            <td>Sp: &nbsp; &nbsp; Speeding</td>
		            <td>Br: &nbsp; &nbsp; Breaking</td>
		            <td>Sf: &nbsp; &nbsp; Safe</td>
		        </tr>
		        <tr>
		        	<td>Wv: &nbsp; &nbsp; Weaving</td>
		            <td>Dr: &nbsp; &nbsp; Drifting</td>
		            <td>Cr: &nbsp; &nbsp; Courteous</td>
		        </tr>
		        <tr>
		        	<td>TG: &nbsp; &nbsp; Tailgating</td>
		            <td>Ph: &nbsp; &nbsp; Phone</td>
		            <td></td>
		        </tr>
		        <tr>
		        	<td>Ct: &nbsp; &nbsp; Cutting</td>
		            <td>DD: &nbsp; &nbsp; Drunk</td>
		            <td></td>
		        </tr>
		        <tr>
		        	<td>O: &nbsp; &nbsp; Other Aggressive</td>
		        	<td></td>
		        	<td></td>
		        </tr>
		    </tbody>
		</table>


	</div>

</section>

app/views/users/_user_forms.html.erb
<!-- Display errors on page: -->
<div class="container">

	<div class="row">

		<% flash.each do |name, msg| -%>
    		<%= content_tag :div, msg, class: name %>
		<% end -%>

	<% if @user %>
		<%= render partial: "shared/form_error_list", locals: { model: @user } %>
	<% end %>
	

	<div class="col-md-4">
		<h2>Registration</h2>
		<%= form_for @user do |f| %>
			
			<p>
				<%= f.text_field :email, :placeholder => "name@example.com" %>
			</p>
			<p>
				<%= f.password_field :password, :placeholder => "password" %>
			</p>
			<p>
				<%= f.password_field :password_confirmation, :placeholder => "password confirmation" %>
			</p>
			<p>
				<%= f.select :license_plate_state, 
			["AL", "AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC","Other"] %>
			</p>
			<p>
				<%= f.text_field :license_plate_number, :placeholder => "License Plate Number" %>
			</p>
			<p>
				<%= f.file_field :vehicle_image, :placeholder => "Vehicle Image" %>
			</p>	
			<p>
				<%= f.submit %>
			</p>

		<% end %>

	</div>
</div>


</div>

app/views/users/index.html.erb
<%= render partial: 'nav_index' %>

<%= render partial: 'landing_page' %>

<%= render partial: 'user_forms' %>

app/views/users/show.html.erb
<%= render partial: 'nav_show' %>


<div class="container" ng-app='myApp'>
	<div class="row">
		<div class="col-md-4">
			<%= render partial: 'profile_corner' %>
		</div>
		<div class="col-md-8">

			<section class="tab" ng-controller="TabController as tab">
				<ul class="nav nav-pills">
					<li ng-class="{ active: tab.isSet(1) }">
						<a href ng-click="tab.setTab(1)">Overall Rating Score</a>
					</li>
					<li ng-class="{ active: tab.isSet(2) }">
						<a href ng-click="tab.setTab(2)">Map</a>
					</li>
					<li ng-class="{ active: tab.isSet(3) }">
						<a href ng-click="tab.setTab(3)">Reviews Feed</a>
					</li>
				</ul>
				
				<div ng-show="tab.isSet(1)">
					<%= render partial: 'score_overall_corner' %>
				</div>
				<div ng-show="tab.isSet(2)">
					<%= render partial: 'map_corner' %>
				</div>
				<div ng-show="tab.isSet(3)">
					<%= render partial: 'score_reviews_corner' %>
				</div>
			</section>

		</div>
	</div>
</div>